### ISSUE TITLE
Not an issue but question/comment

### ISSUE THREAD

**Issue by bekirk** [sduff/restrict_timepicker#1]
I did the following css and got good results but ultimately I want to hide the first and last column in the preset timepicker, also the All time didn't hide either I tried both a "0" and "" for the Earliest value, any thoughts would be great.  Thanks for this it is getting me close to what I want:

`div[id^='dateandtimerange_view'],
div[id^='advanced_view'],
div[id^='relative_view'],
div[id^='realtime_view'] {
        display: none;
}

/* Hide individual items
 */
a[data-earliest="rt-30s"][data-latest="rt"],
a[data-earliest="rt-1m"][data-latest="rt"],
a[data-earliest="rt-5m"][data-latest="rt"],
a[data-earliest="rt-30m"][data-latest="rt"],
a[data-earliest="rt-1h"][data-latest="rt"],
a[data-earliest="rt"][data-latest="rt"],
a[data-earliest="@w0"][data-latest="now"],
a[data-earliest="@w1"][data-latest="now"],
a[data-earliest="-7d@w0"][data-latest="@w0"],
a[data-earliest="-6d@w1"][data-latest="-1d@w6"],
a[data-earliest="-1mon@mon"][data-latest="@mon"],
a[data-earliest="-15m"][data-latest="now"],
a[data-earliest="-60m@m"][data-latest="now"],
a[data-earliest="-4h@m"][data-latest="now"],
a[data-earliest="0"][data-latest="now"] {
        display: none;
}
`

**Comment by sduff** [comment]
Try  `a[data-earliest="0"][data-latest="All time"]` for All TIme, at least on Splunk 7.0.2

**Comment by bekirk** [comment]
You can close this:  Splunk 6.6.2, this works:
`a[data-earliest="0"][data-latest=""]`

Also I was able to add this to my XML code so no need to save static css pages and restart or bump splunk:

```  <row>
    <panel>
        <html depends="$hiddenForCSS$">
         <style>
         div[id^='dateandtimerange_view'],
         div[id^='advanced_view'],
         div[id^='relative_view'],
         div[id^='realtime_view'] {
                 display: none;
         }
         a[data-earliest="rt-30s"][data-latest="rt"],
         a[data-earliest="rt-1m"][data-latest="rt"],
         a[data-earliest="rt-5m"][data-latest="rt"],
         a[data-earliest="rt-30m"][data-latest="rt"],
         a[data-earliest="rt-1h"][data-latest="rt"],
         a[data-earliest="rt"][data-latest="rt"],
         a[data-earliest="@w0"][data-latest="now"],
         a[data-earliest="@w1"][data-latest="now"],
         a[data-earliest="-7d@w0"][data-latest="@w0"],
         a[data-earliest="-6d@w1"][data-latest="-1d@w6"],
         a[data-earliest="-1mon@mon"][data-latest="@mon"],
         a[data-earliest="-15m"][data-latest="now"],
         a[data-earliest="-60m@m"][data-latest="now"],
         a[data-earliest="-4h@m"][data-latest="now"],
         a[data-earliest="0"][data-latest=""] {
                  display: none;
         }
         </style>
       </html>

```

**Comment by mon** [comment]
Good to hear it's working, cheers for the ping
